name: Build and test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: denoland/deno:1.23.1

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task t
