name: Build and test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: denoland/deno:1.23.1

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task t
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "traces-of-darkness"
          entrypoint: "./src/server.ts"
